export const CartActionTypes = {
  TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
  ADD_ITEM: 'ADD_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',
  INCREMENT_ITEM_COUNT: 'INCREMENT_ITEM_COUNT',
  DECREMENT_ITEM_COUNT: 'DECREMENT_ITEM_COUNT'
}